### ISSUE TITLE
New Post, Custom Post Types or Pages won't push.

### ISSUE THREAD

**Issue by akincansenol** [aglipanci/chrome-push-notifications#1]
Hi,

First of all thank you for the give us this important plugin.

But there is a problem, I installed with Wordpress 4.4 and (I don't know may be working well earlier versions of Wordpress) this plugin. When I write new post, page, or anything won't let the push.

I'm sure the options are correctly selected under plugin settings and also on a new entry with push notification button.

But when I try manuel message under plugin admin section "New Message" is correctly working on time.

Thank you again,
Akın

**Comment by aglipanci** [comment]
Hi @akincansenol,
I think @2vpetrov PR solves the issue. Can you try to update from the REPO and let me know?

Thanks,
Agli
