### ISSUE TITLE
Doesn't work when WP URL is not root directory

### ISSUE THREAD

**Issue by AndroPlus-org** [aglipanci/chrome-push-notifications#4]
Hello,

I installed Chrome Push Notifications 1.1.5 on WordPress 4.4 (on nginx 1.9.9 server).
I configured Project Number, GCM API Key (enabled "Google Cloud Messaging for Android" and copied API key of server type) and icon in the admin page,
but all I got in the debug console is:
Init started.
sw.js:25 The ServiceWorker was installed.
sw.js:29 The ServiceWorker was activated.

My website is:
https://androplus.org/

I opened my website in Android's Chrome, but there is no popup for notification.
Is there something I missed, or is this plugin incompatible with WP4.4?

Thank you.

**Comment by aglipanci** [comment]
@AndroPlus-org i have not tested with 4.4 but it should work i think. I have to check and get back at you. While for NGINX i don't there is anything related to webserver.

I am able to access your ServiceWorker and your manifest file here:
https://androplus.org/sw.js
https://androplus.org/manifest.json

**Comment by AndroPlus-org** [comment]
Is the difference of WordPress URL (https://androplus.org/wp) and site URL (https://androplus.org) cause the problem?
sw.js and manifest.json aren't placed at path you posted, but they are at https://androplus.org/wp/.

**Comment by aglipanci** [comment]
They should be in the root directory /

**Comment by AndroPlus-org** [comment]
I changed get_option('siteurl') to get_option('home') and manually copied manifest.json to root directory, and register worked!
I posted test post but notification didn't appear (only log is in Notifications page), so maybe actual fix is needed.

Can you support environment which siteurl is not root directory?

**Comment by AndroPlus-org** [comment]
I made PR, please check if it is correct.
https://github.com/aglipanci/chrome-push-notifications/pull/5
